### ISSUE TITLE
building documantion is broken

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#4653]
Error from PR https://github.com/ComputationalRadiationPhysics/picongpu/pull/4652
It looks like the error is similar to https://github.com/sphinx-doc/sphinx/issues/11605

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/picongpu/envs/4652/lib/python3.11/site-packages/sphinx/cmd/build.py", line 293, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/picongpu/envs/4652/lib/python3.11/site-packages/sphinx/application.py", line 233, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/picongpu/envs/4652/lib/python3.11/site-packages/sphinx/application.py", line 406, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/picongpu/envs/4652/lib/python3.11/site-packages/sphinx/registry.py", line 460, in load_extension
    metadata = setup(app)
               ^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/picongpu/envs/4652/lib/python3.11/site-packages/breathe/__init__.py", line 12, in setup
    directive_setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/picongpu/envs/4652/lib/python3.11/site-packages/breathe/directives/setup.py", line 61, in setup
    project_info_factory = ProjectInfoFactory(app)
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/picongpu/envs/4652/lib/python3.11/site-packages/breathe/project.py", line 116, in __init__
    self._default_build_dir = os.path.dirname(app.doctreedir.rstrip(os.sep))
                                              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute 'rstrip'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/picongpu/envs/4652/lib/python3.11/site-packages/breathe/project.py", line 116, in __init__
    self._default_build_dir = os.path.dirname(app.doctreedir.rstrip(os.sep))
                                              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute 'rstrip'
The full traceback has been saved in /tmp/sphinx-err-vp899j3m.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by PrometheusPi** [comment]
@psychocoderHPC Did #4654 solve this issue?

**Comment by PrometheusPi** [comment]
Okay - the pull request says yes - I will close this issue.
