### ISSUE TITLE
pypicongpu tests broken

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#4853]
Our pypicongpu tests are broken and blocking now other PRs. https://gitlab.com/hzdr/crp/picongpu/-/jobs/6467970644

@BrianMarre COuld you please have a look into pypicongpu tests.

**Comment by psychocoderHPC** [comment]
@BrianMarre said me that TYpeError must be changed into TypeCheckError since typeguard change the error code with version 3.0.0 https://typeguard.readthedocs.io/en/stable/versionhistory.html.

**Comment by psychocoderHPC** [comment]
error:
```
======================================================================
ERROR: test_custom_template_dir_types (quick.picmi.simulation.TestPicmiSimulation)
custom template dir is typechecked
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/hzdr/crp/picongpu/test/python/picongpu/quick/picmi/simulation.py", line 675, in test_custom_template_dir_types
    picmi.Simulation(
  File "/builds/hzdr/crp/picongpu/lib/python/picongpu/picmi/simulation.py", line 96, in __init__
    def __init__(
  File "/miniconda3/envs/pypicongpu/lib/python3.10/site-packages/typeguard/_functions.py", line 136, in check_argument_types
    check_type_internal(value, annotation, memo)
  File "/miniconda3/envs/pypicongpu/lib/python3.10/site-packages/typeguard/_checkers.py", line 779, in check_type_internal
    checker(value, origin_type, args, memo)
  File "/miniconda3/envs/pypicongpu/lib/python3.10/site-packages/typeguard/_checkers.py", line 428, in check_union
    raise TypeCheckError(f"did not match any element in the union:\n{formatted_errors}")
typeguard.TypeCheckError: argument "picongpu_template_dir" (int) did not match any element in the union:
  str: is not an instance of str
  pathlib.Path: is not an instance of pathlib.Path
  NoneType: is not an instance of NoneType
======================================================================
```
